"""fix

Revision ID: 18da71cef97d
Revises: ce384352aeb2
Create Date: 2022-04-26 22:23:05.880839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18da71cef97d'
down_revision = 'ce384352aeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
