"""add column: subsribers_count

Revision ID: 26eb92b3ce1d
Revises: 73fa7762aef4
Create Date: 2022-04-19 18:17:25.441975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26eb92b3ce1d'
down_revision = '73fa7762aef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribers_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribers_count')
    # ### end Alembic commands ###
