"""set default avatar image

Revision ID: 474e3a606bc3
Revises: 92922d95d7b5
Create Date: 2022-04-16 18:14:54.612955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474e3a606bc3'
down_revision = '92922d95d7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
