"""add columns for user notifications and messages count

Revision ID: 667c9dd5cf35
Revises: 474e3a606bc3
Create Date: 2022-04-16 18:20:28.728059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667c9dd5cf35'
down_revision = '474e3a606bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('messages_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'messages_count')
    op.drop_column('users', 'notifications_count')
    # ### end Alembic commands ###
