"""add columns: description, views_count, likes_count, comments_count, video_created

Revision ID: 73fa7762aef4
Revises: 815d09df9ee4
Create Date: 2022-04-19 18:08:07.446806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fa7762aef4'
down_revision = '815d09df9ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('views_count', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('likes_count', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('comments_count', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('video_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'video_created')
    op.drop_column('videos', 'comments_count')
    op.drop_column('videos', 'likes_count')
    op.drop_column('videos', 'views_count')
    op.drop_column('videos', 'description')
    # ### end Alembic commands ###
