"""add created_date column

Revision ID: 940cc0d36ad3
Revises: 18da71cef97d
Create Date: 2022-04-27 18:19:32.375212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940cc0d36ad3'
down_revision = '18da71cef97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('users', 'modified_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modified_date', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###
