"""change default avatar

Revision ID: 9bed272850b1
Revises: 26eb92b3ce1d
Create Date: 2022-04-25 19:58:01.042086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bed272850b1'
down_revision = '26eb92b3ce1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
