"""lazy subquery

Revision ID: cac1002873c7
Revises: 940cc0d36ad3
Create Date: 2022-04-29 16:20:57.679583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac1002873c7'
down_revision = '940cc0d36ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
