"""delete likes_count columns

Revision ID: ce384352aeb2
Revises: 6f35153469e0
Create Date: 2022-04-26 21:39:59.923672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce384352aeb2'
down_revision = '6f35153469e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'likes_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('likes_count', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
