"""add column for liked video and followers with following

Revision ID: e0cbc2a38cc1
Revises: 5b631b143e47
Create Date: 2022-04-26 21:22:36.154552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cbc2a38cc1'
down_revision = '5b631b143e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
